'use client';
import { useState } from 'react';

const products=[
['Нежный рассвет','https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=800&q=85','1290'],
['Пудровая роза','https://images.unsplash.com/photo-1548094990-c16ca90f1f0d?auto=format&fit=crop&w=800&q=85','1690'],
['Облако эустомы','https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=800&q=85','1490'],
['Летний сад','https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=85','1890'],
['Белая классика','https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=800&q=85','1390'],
['Розовый букет','https://images.unsplash.com/photo-1495231916356-a86217efff12?auto=format&fit=crop&w=800&q=85','1590'],
['Авторский букет','https://images.unsplash.com/photo-1509223197845-458d87318791?auto=format&fit=crop&w=800&q=85','2190'],
['Цветы в коробке','https://images.unsplash.com/photo-1455582916367-25f75bfc6710?auto=format&fit=crop&w=800&q=85','2390']
];
const categories=['День рождения','Для любимой','Для мамы','Просто так','Спасибо'];

export default function Home(){
 const [cart,setCart]=useState(0); const [liked,setLiked]=useState<number[]>([]); const [city,setCity]=useState('Киев');
 const toggleLike=(i:number)=>setLiked(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i]);
 return <>
  <div className="topbar"><div className="container"><span>Доставка цветов каждый день · с 9:00 до 22:00</span><div className="toplinks"><span>Помощь</span><span>UAH ₴</span><span>RU</span></div></div></div>
  <header className="header"><div className="container header-main"><div className="logo">Lumière<span>•</span></div><div className="location">📍 Доставка в <b>{city}</b></div><div className="search"><input placeholder="Найти букет, розы или подарок…"/></div><div className="icons"><button className="iconbtn hide-mobile" aria-label="Избранное">♡</button><button className="iconbtn" onClick={()=>setCart(v=>v+1)} aria-label="Корзина">🛍️<sup>{cart}</sup></button></div></div><nav className="nav"><div className="container"><a className="sale" href="#catalog">Акции</a><a href="#catalog">Новинки</a><a href="#catalog">Хиты продаж</a><a href="#catalog">Букеты</a><a href="#catalog">Розы</a><a href="#catalog">Цветы в коробке</a><a href="#catalog">Подарки</a><a href="#delivery">Доставка</a></div></nav></header>
  <main>
   <section className="hero"><div className="container"><div className="hero-card"><div className="hero-copy"><div className="eyebrow">Lumière flowers</div><h1>Цветы, которые говорят за вас</h1><p>Свежие букеты от флористов. Соберём заказ сегодня и бережно доставим получателю.</p><a className="btn light" href="#catalog">Выбрать букет</a></div></div></div></section>
   <section><div className="container"><div className="section-head"><h2>Выбирайте по поводу</h2></div><div className="chips">{categories.map(x=><a className="chip" href="#catalog" key={x}>{x} <span>→</span></a>)}</div></div></section>
   <section id="catalog"><div className="container"><div className="section-head"><h2>Хиты продаж</h2><a href="#catalog">Смотреть все →</a></div><div className="products">{products.map((p,i)=><article className="product" key={p[0]}><button className="heart" onClick={()=>toggleLike(i)}>{liked.includes(i)?'♥':'♡'}</button>{i<2&&<span className="badge">ХИТ</span>}<div className="product-img"><img src={p[1]} alt={p[0]}/></div><h3>{p[0]}</h3><div className="price">{p[2]} ₴ <span className="old">{i%2===0?'1490':''}</span></div><button className="btn" style={{marginTop:12,width:'100%'}} onClick={()=>setCart(v=>v+1)}>Добавить в корзину</button></article>)}</div></div></section>
   <div className="trust"><div className="container trust-grid"><div className="trust-item"><div className="trust-icon">✿</div><div><strong>Свежие цветы</strong><span>Получаем поставки несколько раз в неделю</span></div></div><div className="trust-item"><div className="trust-icon">⏱</div><div><strong>Доставка от 2 часов</strong><span>Выберите удобный интервал при оформлении</span></div></div><div className="trust-item"><div className="trust-icon">♡</div><div><strong>Фото перед доставкой</strong><span>Покажем готовый букет перед отправкой</span></div></div><div className="trust-item"><div className="trust-icon">✓</div><div><strong>Гарантия качества</strong><span>Если что-то не так — обязательно исправим</span></div></div></div></div>
   <section id="delivery"><div className="container delivery"><div><h2>Подарок сегодня — без лишних хлопот</h2><p>Оформите заказ онлайн, укажите адрес и время. Флорист соберёт букет вручную, а курьер аккуратно доставит его получателю.</p><p><b>Доставка по {city}</b> · с 9:00 до 22:00</p><a className="btn" href="#catalog">Заказать доставку</a></div><img src="https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1000&q=85" alt="Букет цветов"/></div></section>
   <section><div className="container"><div className="section-head"><h2>Нас выбирают за эмоции</h2></div><div className="reviews"><div className="review"><div className="stars">★★★★★</div><p>«Букет оказался даже красивее, чем на фото. Доставили вовремя, всё очень аккуратно.»</p><strong>Анна · Киев</strong></div><div className="review"><div className="stars">★★★★★</div><p>«Заказывал сюрприз утром — уже после обеда получатель прислал фото. Отличный сервис.»</p><strong>Максим · Львов</strong></div><div className="review"><div className="stars">★★★★★</div><p>«Понравилось, что перед отправкой показали букет. Цветы свежие, упаковка стильная.»</p><strong>Ольга · Одесса</strong></div></div></div></section>
  </main>
  <footer className="footer"><div className="container"><div className="footer-grid"><div><h3>Lumière<span>•</span></h3><p>Цветы и подарки с доставкой. Создаём красивые поводы каждый день.</p></div><div><h4>Каталог</h4><a href="#catalog">Букеты</a><a href="#catalog">Розы</a><a href="#catalog">Новинки</a><a href="#catalog">Подарки</a></div><div><h4>Помощь</h4><a href="#delivery">Доставка</a><a href="#delivery">Оплата</a><a href="#delivery">Гарантия</a><a href="#delivery">Контакты</a></div><div><h4>Города</h4><a href="#">Киев</a><a href="#">Львов</a><a href="#">Одесса</a><a href="#">Днепр</a></div></div><div className="bottom">© 2026 Lumière Flowers · Сделано с любовью к цветам</div></div></footer>
 </>
}